model_list:
  - model_name: qwen36-35b-heretic
    litellm_params:
      model: openai/qwen36-35b-heretic
      api_base: http://192.168.0.33:8000/v1
      api_key: local-key
      timeout: 120


general_settings:
  master_key: sk-local-agentstack

router_settings:
  routing_strategy: simple-shuffle
  num_retries: 2
  timeout: 120
