events {}
http {
    upstream spark {
        server 192.168.0.33:8000;
    }
    server {
        listen 8000;
        location / {
            proxy_pass http://spark;
            proxy_read_timeout 120s;
            proxy_connect_timeout 120s;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
