use crate::feature_extraction_types::FeatureRecord;
use deadpool_postgres::Pool;

pub async fn persist_feature_record(
    pool: &Pool,
    record: &FeatureRecord,
) -> Result<(), anyhow::Error> {
    let started = std::time::Instant::now();
    let result = async {
        let conn = pool.get().await?;
        let failure_classes = serde_json::to_value(&record.failure_classes)?;
        let recommended_constraints = serde_json::to_value(&record.recommended_constraints)?;
        let suppressed_constraints = serde_json::to_value(&record.suppressed_constraints)?;
        conn.execute(
            "INSERT INTO agent_feature_records (
                feature_id, trajectory_id, session_id, repo, window_start, window_end,
                event_count, user_message_count, assistant_message_count, failed_attempt_count,
                summary_count, tool_loop_count, repeated_read_loop_count, repeated_bash_loop_count,
                user_interruption_count, missing_auth_count, wrong_endpoint_count,
                summarization_failure_count, migration_failure_count, other_failure_count,
                context_pack_empty_count, context_pack_truncated_count, high_input_token_count,
                slow_upstream_model_count, empty_tool_use_message_count,
                abandoned_before_model_count, single_model_abandoned_no_tools_count,
                summarizer_shared_upstream_count,
                known_endpoint, known_auth_header, known_migration_fix, loop_detected,
                user_interrupted, failure_classes, recommended_constraints, suppressed_constraints,
                created_at, updated_at
             )
             VALUES (
                $1, $2, $3, $4, $5, $6,
                $7, $8, $9, $10,
                $11, $12, $13, $14,
                $15, $16, $17,
                $18, $19, $20,
                $21, $22, $23, $24,
                $25, $26, $27, $28,
                $29, $30, $31, $32,
                $33, $34, $35, $36,
                now(), now()
             )
             ON CONFLICT (feature_id)
             DO UPDATE SET
                trajectory_id = EXCLUDED.trajectory_id,
                session_id = EXCLUDED.session_id,
                repo = EXCLUDED.repo,
                window_start = EXCLUDED.window_start,
                window_end = EXCLUDED.window_end,
                event_count = EXCLUDED.event_count,
                user_message_count = EXCLUDED.user_message_count,
                assistant_message_count = EXCLUDED.assistant_message_count,
                failed_attempt_count = EXCLUDED.failed_attempt_count,
                summary_count = EXCLUDED.summary_count,
                tool_loop_count = EXCLUDED.tool_loop_count,
                repeated_read_loop_count = EXCLUDED.repeated_read_loop_count,
                repeated_bash_loop_count = EXCLUDED.repeated_bash_loop_count,
                user_interruption_count = EXCLUDED.user_interruption_count,
                missing_auth_count = EXCLUDED.missing_auth_count,
                wrong_endpoint_count = EXCLUDED.wrong_endpoint_count,
                summarization_failure_count = EXCLUDED.summarization_failure_count,
                migration_failure_count = EXCLUDED.migration_failure_count,
                other_failure_count = EXCLUDED.other_failure_count,
                context_pack_empty_count = EXCLUDED.context_pack_empty_count,
                context_pack_truncated_count = EXCLUDED.context_pack_truncated_count,
                high_input_token_count = EXCLUDED.high_input_token_count,
                slow_upstream_model_count = EXCLUDED.slow_upstream_model_count,
                empty_tool_use_message_count = EXCLUDED.empty_tool_use_message_count,
                abandoned_before_model_count = EXCLUDED.abandoned_before_model_count,
                single_model_abandoned_no_tools_count = EXCLUDED.single_model_abandoned_no_tools_count,
                summarizer_shared_upstream_count = EXCLUDED.summarizer_shared_upstream_count,
                known_endpoint = EXCLUDED.known_endpoint,
                known_auth_header = EXCLUDED.known_auth_header,
                known_migration_fix = EXCLUDED.known_migration_fix,
                loop_detected = EXCLUDED.loop_detected,
                user_interrupted = EXCLUDED.user_interrupted,
                failure_classes = EXCLUDED.failure_classes,
                recommended_constraints = EXCLUDED.recommended_constraints,
                suppressed_constraints = EXCLUDED.suppressed_constraints,
                updated_at = CASE
                    WHEN (
                        agent_feature_records.trajectory_id,
                        agent_feature_records.session_id,
                        agent_feature_records.repo,
                        agent_feature_records.window_start,
                        agent_feature_records.window_end,
                        agent_feature_records.event_count,
                        agent_feature_records.user_message_count,
                        agent_feature_records.assistant_message_count,
                        agent_feature_records.failed_attempt_count,
                        agent_feature_records.summary_count,
                        agent_feature_records.tool_loop_count,
                        agent_feature_records.repeated_read_loop_count,
                        agent_feature_records.repeated_bash_loop_count,
                        agent_feature_records.user_interruption_count,
                        agent_feature_records.missing_auth_count,
                        agent_feature_records.wrong_endpoint_count,
                        agent_feature_records.summarization_failure_count,
                        agent_feature_records.migration_failure_count,
                        agent_feature_records.other_failure_count,
                        agent_feature_records.context_pack_empty_count,
                        agent_feature_records.context_pack_truncated_count,
                        agent_feature_records.high_input_token_count,
                        agent_feature_records.slow_upstream_model_count,
                        agent_feature_records.empty_tool_use_message_count,
                        agent_feature_records.abandoned_before_model_count,
                        agent_feature_records.single_model_abandoned_no_tools_count,
                        agent_feature_records.summarizer_shared_upstream_count,
                        agent_feature_records.known_endpoint,
                        agent_feature_records.known_auth_header,
                        agent_feature_records.known_migration_fix,
                        agent_feature_records.loop_detected,
                        agent_feature_records.user_interrupted,
                        agent_feature_records.failure_classes,
                        agent_feature_records.recommended_constraints,
                        agent_feature_records.suppressed_constraints
                    ) IS DISTINCT FROM (
                        EXCLUDED.trajectory_id,
                        EXCLUDED.session_id,
                        EXCLUDED.repo,
                        EXCLUDED.window_start,
                        EXCLUDED.window_end,
                        EXCLUDED.event_count,
                        EXCLUDED.user_message_count,
                        EXCLUDED.assistant_message_count,
                        EXCLUDED.failed_attempt_count,
                        EXCLUDED.summary_count,
                        EXCLUDED.tool_loop_count,
                        EXCLUDED.repeated_read_loop_count,
                        EXCLUDED.repeated_bash_loop_count,
                        EXCLUDED.user_interruption_count,
                        EXCLUDED.missing_auth_count,
                        EXCLUDED.wrong_endpoint_count,
                        EXCLUDED.summarization_failure_count,
                        EXCLUDED.migration_failure_count,
                        EXCLUDED.other_failure_count,
                        EXCLUDED.context_pack_empty_count,
                        EXCLUDED.context_pack_truncated_count,
                        EXCLUDED.high_input_token_count,
                        EXCLUDED.slow_upstream_model_count,
                        EXCLUDED.empty_tool_use_message_count,
                        EXCLUDED.abandoned_before_model_count,
                        EXCLUDED.single_model_abandoned_no_tools_count,
                        EXCLUDED.summarizer_shared_upstream_count,
                        EXCLUDED.known_endpoint,
                        EXCLUDED.known_auth_header,
                        EXCLUDED.known_migration_fix,
                        EXCLUDED.loop_detected,
                        EXCLUDED.user_interrupted,
                        EXCLUDED.failure_classes,
                        EXCLUDED.recommended_constraints,
                        EXCLUDED.suppressed_constraints
                    )
                    THEN now()
                    ELSE agent_feature_records.updated_at
                END",
            &[
                &record.feature_id,
                &record.trajectory_id,
                &record.session_id,
                &record.repo,
                &record.window_start,
                &record.window_end,
                &record.event_count,
                &record.user_message_count,
                &record.assistant_message_count,
                &record.failed_attempt_count,
                &record.summary_count,
                &record.tool_loop_count,
                &record.repeated_read_loop_count,
                &record.repeated_bash_loop_count,
                &record.user_interruption_count,
                &record.missing_auth_count,
                &record.wrong_endpoint_count,
                &record.summarization_failure_count,
                &record.migration_failure_count,
                &record.other_failure_count,
                &record.context_pack_empty_count,
                &record.context_pack_truncated_count,
                &record.high_input_token_count,
                &record.slow_upstream_model_count,
                &record.empty_tool_use_message_count,
                &record.abandoned_before_model_count,
                &record.single_model_abandoned_no_tools_count,
                &record.summarizer_shared_upstream_count,
                &record.known_endpoint,
                &record.known_auth_header,
                &record.known_migration_fix,
                &record.loop_detected,
                &record.user_interrupted,
                &failure_classes,
                &recommended_constraints,
                &suppressed_constraints,
            ],
        )
        .await?;
        Ok(())
    }
    .await;
    crate::telemetry::record_db_query("feature_persist_record", started.elapsed(), result.is_ok());
    result
}
