// Top-level modules.
pub mod adversarial_harness;
pub mod anthropic;
pub mod anthropic_user_content;
pub mod app_router;
pub mod auth;
pub mod background;
pub mod client_capture;
pub mod client_capture_types;
pub mod context_artifacts;
pub mod context_compiler;
pub mod context_ledger;
pub mod context_packing;
pub mod context_rendering;
pub mod context_search;
pub mod db;
pub mod embedder;
pub mod event_capture;
pub mod execution_feedback;
pub mod feature_extraction;
pub mod handlers;
pub mod harness_feedback;
pub mod hybrid;
pub mod litellm;
pub mod local_reasoning;
pub mod logging;
pub mod migrations;
pub mod orchestration_policy;
pub mod prompt_intervention;
pub mod proxy_support;
pub mod qdrant;
pub mod rate_limit;
pub mod request_classification;
pub mod request_policy;
pub mod request_policy_responses;
pub mod routes;
pub mod sampling;
pub mod sentiment;
pub mod sse;
pub mod startup;
pub mod state;
pub mod summarizer;
pub mod system_context;
pub mod telemetry;
pub mod token_limits;
pub mod tool_mediation;
pub mod total_recall;
pub mod trajectory;
pub mod vllm;

#[cfg(test)]
mod hybrid_tests;

// Compatibility aliases for pre-directory module paths.
pub use adversarial_harness::callback_normalization as adversarial_harness_callback_normalization;
pub use adversarial_harness::callbacks as adversarial_harness_callbacks;
pub use adversarial_harness::outcome as adversarial_harness_outcome;

pub use context_compiler::event_artifacts as context_compiler_event_artifacts;
pub use context_compiler::instructions as context_compiler_instructions;
pub use context_compiler::support as context_compiler_support;
pub use context_compiler::total_recall as context_compiler_total_recall;

pub use context_packing::build as context_packing_build;
pub use context_packing::cache as context_packing_cache;
pub use context_packing::endpoint as context_packing_endpoint;
pub use context_packing::policy as context_packing_policy;

pub use context_rendering::event_lines as context_rendering_event_lines;
pub use context_rendering::failure_sections as context_rendering_failure_sections;
pub use context_rendering::flat as context_rendering_flat;
pub use context_rendering::sections as context_rendering_sections;

pub use db::connection as db_connection;
pub use db::context_artifact_candidates as db_context_artifact_candidates;
pub use db::context_artifacts as db_context_artifacts;
pub use db::context_compiler_ledger as db_context_compiler_ledger;
pub use db::context_event_queries as db_context_event_queries;
pub use db::context_events as db_context_events;
pub use db::context_search as db_context_search;
pub use db::error_index as db_error_index;
pub use db::event_rows as db_event_rows;
pub use db::execution_events as db_execution_events;
pub use db::failure_remediation as db_failure_remediation;
pub use db::failures as db_failures;
pub use db::sessions as db_sessions;
pub use db::trajectory as db_trajectory;
pub use db::trajectory_queries as db_trajectory_queries;
pub use db::trajectory_results as db_trajectory_results;
pub use db::types as db_types;
pub use db::usage as db_usage;

pub use event_capture::background as event_capture_background;
pub use event_capture::context as event_capture_context;
pub use event_capture::exchange as event_capture_exchange;
pub use event_capture::request as event_capture_request;
pub use event_capture::tool_results as event_capture_tool_results;

pub use execution_feedback::chain as execution_feedback_chain;
pub use execution_feedback::compile_payloads as execution_feedback_compile_payloads;
pub use execution_feedback::events as execution_feedback_events;
pub use execution_feedback::fingerprint_rules as execution_feedback_fingerprint_rules;
pub use execution_feedback::fingerprints as execution_feedback_fingerprints;
pub use execution_feedback::labels as execution_feedback_labels;
pub use execution_feedback::lint_payloads as execution_feedback_lint_payloads;
pub use execution_feedback::parsing as execution_feedback_parsing;
pub use execution_feedback::payloads as execution_feedback_payloads;
pub use execution_feedback::reports as execution_feedback_reports;
pub use execution_feedback::signature_payloads as execution_feedback_signature_payloads;
pub use execution_feedback::summaries as execution_feedback_summaries;
pub use execution_feedback::test_payloads as execution_feedback_test_payloads;
pub use execution_feedback::tool_events as execution_feedback_tool_events;
pub use execution_feedback::tool_result as execution_feedback_tool_result;
pub use execution_feedback::validation_payloads as execution_feedback_validation_payloads;
pub use execution_feedback::validation_result_payloads as execution_feedback_validation_result_payloads;
pub use execution_feedback::validators as execution_feedback_validators;

pub use feature_extraction::config as feature_extraction_config;
pub use feature_extraction::constraint_budget as feature_constraint_budget;
pub use feature_extraction::constraint_failures as feature_constraint_failures;
pub use feature_extraction::constraint_suppression as feature_constraint_suppression;
pub use feature_extraction::constraint_templates as feature_constraint_templates;
pub use feature_extraction::constraints as feature_constraints;
pub use feature_extraction::detection_bootstrap as feature_detection_bootstrap;
pub use feature_extraction::detection_event_rules as feature_detection_event_rules;
pub use feature_extraction::detection_event_type_rules as feature_detection_event_type_rules;
pub use feature_extraction::detection_producer_signals as feature_detection_producer_signals;
pub use feature_extraction::detection_tag_merge as feature_detection_tag_merge;
pub use feature_extraction::detection_tags as feature_detection_tags;
pub use feature_extraction::env as feature_extraction_env;
pub use feature_extraction::grouping as feature_extraction_grouping;
pub use feature_extraction::inline as feature_extraction_inline;
pub use feature_extraction::metadata as feature_extraction_metadata;
pub use feature_extraction::metadata_paths as feature_metadata_paths;
pub use feature_extraction::metadata_summarizer as feature_metadata_summarizer;
pub use feature_extraction::metadata_trajectory as feature_metadata_trajectory;
pub use feature_extraction::persistence as feature_extraction_persistence;
pub use feature_extraction::persistence_sql as feature_extraction_persistence_sql;
pub use feature_extraction::queries as feature_extraction_queries;
pub use feature_extraction::record_init as feature_extraction_record_init;
pub use feature_extraction::records as feature_extraction_records;
pub use feature_extraction::recovery as feature_extraction_recovery;
pub use feature_extraction::store as feature_extraction_store;
pub use feature_extraction::tags as feature_extraction_tags;
pub use feature_extraction::types as feature_extraction_types;

pub use handlers::anthropic_completion as handlers_anthropic_completion;
pub use handlers::anthropic_dispatch as handlers_anthropic_dispatch;
pub use handlers::anthropic_json_upstream as handlers_anthropic_json_upstream;
pub use handlers::anthropic_messages as handlers_anthropic_messages;
pub use handlers::anthropic_persistence as handlers_anthropic_persistence;
pub use handlers::anthropic_stream_upstream as handlers_anthropic_stream_upstream;
pub use handlers::anthropic_streaming as handlers_anthropic_streaming;
pub use handlers::anthropic_upstream as handlers_anthropic_upstream;
pub use handlers::capture as handlers_capture;
pub use handlers::chat_completions as handlers_chat_completions;
pub use handlers::context as handlers_context;
pub use handlers::litellm_attempt as handlers_litellm_attempt;
pub use handlers::openai_dispatch as handlers_openai_dispatch;
pub use handlers::openai_persistence as handlers_openai_persistence;
pub use handlers::openai_upstream as handlers_openai_upstream;
pub use handlers::request as handlers_request;
pub use handlers::request_preparation as handlers_request_preparation;
pub use handlers::stream_persistence as handlers_stream_persistence;
pub use handlers::stream_persistence_types as handlers_stream_persistence_types;
pub use handlers::streaming as handlers_streaming;
pub use handlers::trajectory as handlers_trajectory;
pub use handlers::usage as handlers_usage;

pub use harness_feedback::classification as harness_feedback_classification;
pub use harness_feedback::guardrail as harness_feedback_guardrail;
pub use harness_feedback::metadata as harness_feedback_metadata;
pub use harness_feedback::store as harness_feedback_store;
pub use harness_feedback::taxonomy as harness_feedback_taxonomy;
pub use harness_feedback::text_signals as harness_feedback_text_signals;

pub use litellm::cache as litellm_cache;
pub use litellm::ledger as litellm_ledger;
pub use litellm::ledger_persistence as litellm_ledger_persistence;
pub use litellm::provider_cache as litellm_provider_cache;

pub use orchestration_policy::base as orchestration_policy_base;
pub use orchestration_policy::context_types as orchestration_policy_context_types;
pub use orchestration_policy::intents as orchestration_policy_intents;
pub use orchestration_policy::intents_mutating as orchestration_policy_intents_mutating;
pub use orchestration_policy::intents_read as orchestration_policy_intents_read;
pub use orchestration_policy::overlay_types as orchestration_policy_overlay_types;
pub use orchestration_policy::overlays as orchestration_policy_overlays;
pub use orchestration_policy::posture_types as orchestration_policy_posture_types;
pub use orchestration_policy::store as orchestration_policy_store;
pub use orchestration_policy::tool_types as orchestration_policy_tool_types;
pub use orchestration_policy::types as orchestration_policy_types;

pub use prompt_intervention::assembly as prompt_intervention_assembly;
pub use prompt_intervention::backfill as prompt_intervention_backfill;
pub use prompt_intervention::detector as prompt_intervention_detector;
pub use prompt_intervention::extraction as prompt_intervention_extraction;
pub use prompt_intervention::fingerprint as prompt_intervention_fingerprint;
pub use prompt_intervention::records as prompt_intervention_records;
pub use prompt_intervention::report as prompt_intervention_report;
pub use prompt_intervention::taxonomy as prompt_intervention_taxonomy;
pub use prompt_intervention::telemetry as telemetry_prompt_interventions;

pub use request_classification::backfill as request_classification_backfill;
pub use request_classification::backfill_queries as request_classification_backfill_queries;
pub use request_classification::bindings as request_classification_bindings;
pub use request_classification::composition as request_classification_composition;
pub use request_classification::config as request_classification_config;
pub use request_classification::feature_json as request_classification_feature_json;
pub use request_classification::feature_keys as request_classification_feature_keys;
pub use request_classification::feature_vocab as request_classification_feature_vocab;
pub use request_classification::features as request_classification_features;
pub use request_classification::fragments as request_classification_fragments;
pub use request_classification::input as request_classification_input;
pub use request_classification::labels as request_classification_labels;
pub use request_classification::report as request_classification_report;
pub use request_classification::routing as request_classification_routing;
pub use request_classification::rule_complexity as request_classification_rule_complexity;
pub use request_classification::rule_context as request_classification_rule_context;
pub use request_classification::rule_intent as request_classification_rule_intent;
pub use request_classification::rule_risk as request_classification_rule_risk;
pub use request_classification::rule_utils as request_classification_rule_utils;
pub use request_classification::rules as request_classification_rules;
pub use request_classification::runtime as request_classification_runtime;
pub use request_classification::store as request_classification_store;
pub use request_classification::store_telemetry as request_classification_store_telemetry;
pub use request_classification::taxonomy as request_classification_taxonomy;
pub use request_classification::telemetry as telemetry_request_classification;
pub use request_classification::types as request_classification_types;

pub use sampling::audit as sampling_audit;

pub use startup::backfill as startup_backfill;
pub use startup::config as startup_config;
pub use startup::env as startup_env;
pub use startup::harness_feedback as startup_harness_feedback;
pub use startup::runtime as startup_runtime;

pub use state::api_types as state_api_types;
pub use state::context as state_context;
pub use state::context_cache as state_context_cache;
pub use state::context_policy as state_context_policy;
pub use state::limits as state_limits;
pub use state::summarizer as state_summarizer;
pub use state::task_category as state_task_category;
pub use state::token_usage as state_token_usage;

pub use summarizer::candidates as summarizer_candidates;
pub use summarizer::failures as summarizer_failures;
pub use summarizer::levels as summarizer_levels;
pub use summarizer::persistence as summarizer_persistence;
pub use summarizer::promotion as summarizer_promotion;
pub use summarizer::upstream as summarizer_upstream;

pub use telemetry::context as telemetry_context;
pub use telemetry::descriptions as telemetry_descriptions;
pub use telemetry::descriptions_execution as telemetry_descriptions_execution;
pub use telemetry::descriptions_model_context as telemetry_descriptions_model_context;
pub use telemetry::descriptions_request as telemetry_descriptions_request;
pub use telemetry::descriptions_runtime as telemetry_descriptions_runtime;
pub use telemetry::descriptions_transport as telemetry_descriptions_transport;
pub use telemetry::execution as telemetry_execution;
pub use telemetry::feature_feedback as telemetry_feature_feedback;
pub use telemetry::http as telemetry_http;
pub use telemetry::infrastructure as telemetry_infrastructure;
pub use telemetry::model_services as telemetry_model_services;
pub use telemetry::prime_feedback as telemetry_prime_feedback;
pub use telemetry::prime_runtime as telemetry_prime_runtime;
pub use telemetry::recorder as telemetry_recorder;
pub use telemetry::request_policy_prime as telemetry_request_policy_prime;
pub use telemetry::runtime_metrics as telemetry_runtime_metrics;
pub use telemetry::setup as telemetry_setup;
pub use telemetry::streaming as telemetry_streaming;
pub use telemetry::upstream as telemetry_upstream;
pub use telemetry::usage as telemetry_usage;
pub use tool_mediation::telemetry as telemetry_tool_mediation;

pub use tool_mediation::authorization as tool_mediation_authorization;
pub use tool_mediation::authorization_types as tool_mediation_authorization_types;
pub use tool_mediation::canonical as tool_mediation_canonical;
pub use tool_mediation::classification as tool_mediation_classification;
pub use tool_mediation::payload as tool_mediation_payload;
pub use tool_mediation::policy as tool_mediation_policy;
pub use tool_mediation::shaping as tool_mediation_shaping;
pub use tool_mediation::shaping_policy as tool_mediation_shaping_policy;
pub use tool_mediation::shell as tool_mediation_shell;
pub use tool_mediation::types as tool_mediation_types;

pub use trajectory::event_payload as trajectory_event_payload;
pub use trajectory::events as trajectory_events;
pub use trajectory::roles as trajectory_roles;
pub use trajectory::summary as trajectory_summary;
pub use trajectory::summary_status as trajectory_summary_status;
pub use trajectory::types as trajectory_types;

pub use vllm as vllm_metrics;
pub use vllm::cache_usage as vllm_cache_usage;
pub use vllm::metrics_snapshot as vllm_metrics_snapshot;
